"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "@/components/admin/Navbar";
import { SidebarAdmin, SidebarSiswa, SidebarSiswaProfile } from "@/components/SideBar";
import { usePathname } from "next/navigation";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

// export const metadata: Metadata = {
//   title: "Simon PKL",
//   description: "Generated by create next app",
// };

const disableNavSidebar = ["/login", "/register"];
const siswaPagesWithoutNavSidebar = ["/siswa/profile"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role: string = "admin";

  const pathname = usePathname();
  const isSiswaPage = pathname.startsWith("/siswa");
  const isSiswaPageProfile = pathname.startsWith("/siswa/profile");
  const isDisableNavSidebar = disableNavSidebar.includes(pathname);
  const isSiswaPageWithoutNavSidebar =
    siswaPagesWithoutNavSidebar.includes(pathname);

  return (
    <html lang="en">
      <body
        className={montserrat.className}
        // style={{ backgroundColor: "#EAEAEA" }}
        suppressHydrationWarning={true}
      >
        {!isDisableNavSidebar && (
          <>
            <Navbar />
            <div className="flex">
              {isSiswaPage ? <SidebarSiswa /> : <SidebarAdmin />}
              <div className="">{children}</div>
            </div>
          </>
        )}

      </body>
    </html>
  );
}
